spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shopping_cart_circuitbreaker_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - CircuitBreaker=myCircuitBreaker
            - PrefixPath=/api/v1
        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
        - id: warehouse_service_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1
server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.boot.actuate: TRACE
    org.springframework.cloud.loadbalancer: DEBUG