spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4432/delivery-db
    username: delivery
    password: delivery

delivery:
  base_cost: 5.0
  warehouse_address_ratio: 2
  fragile_ratio: 0.2
  weight_ratio: 0.3
  volume_ratio: 0.2
  delivery_address_ratio: 0.2