spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: HubEventConsumer
      group-id: hubEvent.group.id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: deserializer.HubEventDeserializer
      enable-auto-commit: false
      snapshots:
        client-id: SnapshotsConsumer
        group-id: snapshot.group.id
        deserializer: deserializer.SnapshotDeserializer

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scenario-db
    username: username
    password: password

topic:
  snapshots-topic: telemetry.snapshots.v1
  hub-event-topic: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

threadPool:
  arrayBlockingQueue:
    capacity: 2
  corePoolSize: 2
  maximumPoolSize: 2
  keepAliveTime: 60