spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      client-id: HubEventConsumer
      group-id: hubEvent.group.id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: deserializer.HubEventDeserializer
      enable-auto-commit: false

      snapshots:
        client-id: SnapshotsConsumer
        group-id: snapshot.group.id
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: deserializer.SnapshotDeserializer
        enable-auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scenario-db
    username: username
    password: password

kafka:
  topics:
    hub-events: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: discovery://hub-router
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext